1. Вывести все поля и все строки.

select * from students;

2. Вывести всех студентов в таблице.

select * from students;

3. Вывести только Id пользователей.

select id from students;

4. Вывести только имя пользователей.

select name from students;

5. Вывести только email пользователей.

6. Вывести имя и email пользователей.

select name, email from students;

7. Вывести id, имя, email и дату создания пользователей.

8. Вывести пользователей где password 12333.

select * from students
where password = '12333';

select id, name, email, created_on from students;

